### PR TITLE
Feature: enumerations.

### LINKED ISSUE #5: Incompatible encoding of enumerations.
By an _«enumeration»_ I mean a data type whose constructors are all nullary. By default, Aeson encodes the values of such types as strings identical to constructor names, rather than as objects of form `{"tag": …}`. This particularity is not reflected in this package, resulting in errors when decoding such types.

I am going to fix this and make a pull request within a week.

### PR DESCRIPTION
**Pull request by kindaro**
Resolve #5.

### CODE REVIEW

**Comment by kindaro** [comment]
The work so far shows how some combinations of options and data shapes result in failure to decode from Aeson. Amusingly, the unit type is not always decoded correctly!

**Comment by kindaro** [comment]
The work is now complete.

You may see that I replaced the test suite completely. Note that the previous tests were removed only after all the modifications to the library were in place, so we know that everything those tests used to check remains correct. The new test suite is much more comprehensive and I made every effort to ensure that it aligns with Haskell's Aeson — the string values to compare against were generated by a Haskell script.

**Comment by kindaro** [comment]
Resolve #8.

**Comment by kindaro** [comment]
Close #8.

**Comment by kindaro** [comment]
Should we bump version, put a tag on it, and all such?

**Comment by StephenWakely** [comment]
Yeah, that's some beautiful work there! Thankyou so much.

Good point on the versions. I'll bump it.

**Pull request merged**
