### PR TITLE
Fix single constructor types.

### LINKED ISSUE #1: Incompatible encoding of single-constructor data types
Aeson, with `defaultOptions` (and also `defaultOptions { allNullaryToStringTag = True }`), encodes single-constructor records without a tag field. Example:

```
$ stack ghci --resolver lts-11.9 --package aeson
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
λ> import qualified Data.Aeson as A
λ> :set -XDeriveGeneric
λ> :m + GHC.Generics
λ> data SC = SC { x :: Int, y :: Int } deriving (Generic)
λ> A.genericToJSON A.defaultOptions { A.allNullaryToStringTag = True } SC { x = 1, y = 2 }
Object (fromList [("x",Number 1.0),("y",Number 2.0)])
```

`purescript-argonaut-aeson-generic` doesn't correctly decode this format. Here's a test case:

```diff
diff --git a/test/Main.purs b/test/Main.purs
index e0c4c71..b0100b0 100644
--- a/test/Main.purs
+++ b/test/Main.purs
@@ -7,7 +7,7 @@ import Data.Argonaut (encodeJson)
 import Data.Argonaut.Aeson.Decode.Generic (genericDecodeAeson)
 import Data.Argonaut.Aeson.Encode.Generic (genericEncodeAeson)
 import Data.Argonaut.Aeson.Options (Options(..), SumEncoding(..))
-import Data.Argonaut.Core (toObject)
+import Data.Argonaut.Core (fromObject, toObject)
 import Data.Either (Either(..))
 import Data.Generic.Rep (class Generic)
 import Data.Maybe (Maybe(..))
@@ -34,6 +34,12 @@ instance showD :: Show D where
   show (Binary a b) = "Binary " <> show a <> " " <> show b
   show (Rec a) = "Rec { x: " <> show a.x <> ", y: " <> show a.y <> "}"
 
+newtype SC = SC { x :: Int, y :: Int }
+derive instance eqSC :: Eq SC
+derive instance gSC :: Generic SC _
+instance showSC :: Show SC where
+  show (SC a) = "SC { x: " <> show a.x <> ", y: " <> show a.y <> " }"
+
 unsafeLog :: forall a e. a -> Eff (console :: CONSOLE | e) Unit
 unsafeLog = log <<< unsafeCoerce
 
@@ -56,6 +62,9 @@ main = runTest do
     test "Record" do
       let o = toObject $ genericEncodeAeson opts (Rec {x: 1, y: 2})
       Assert.equal (Just $ SM.fromFoldable ["TAG" /\ encodeJson "Rec", "x" /\ encodeJson 1, "y" /\ encodeJson 2]) o
+    test "Single constructor" do
+      let o = toObject $ genericEncodeAeson opts (SC {x: 1, y: 2})
+      Assert.equal (Just $ SM.fromFoldable ["x" /\ encodeJson 1, "y" /\ encodeJson 2]) o
 
   suite "Decode" do
     test "Nullary" do
@@ -70,3 +79,6 @@ main = runTest do
     test "Record" do
       let o = genericEncodeAeson opts (Rec {x: 1, y: 2})
       Assert.equal (Right (Rec {x: 1, y: 2})) (genericDecodeAeson opts o)
+    test "Single constructor" do
+      let o = fromObject $ SM.fromFoldable ["x" /\ encodeJson 1, "y" /\ encodeJson 2]
+      Assert.equal (Right (SC {x: 1, y: 2})) (genericDecodeAeson opts o)
```

Fails with:

```
→ Suite: Aeson encoding
  ☠ Failed: Single constructor because expected (Just (fromFoldable [(Tuple "x" 1),(Tuple "y" 2)])), got (Just (fromFoldable [(Tuple "y" 2),(Tuple "x" 1),(Tuple "TAG" "SC")]))
→ Suite: Decode
  ☠ Failed: Single constructor because expected (Right SC { x: 1, y: 2 }), got (Left "When decoding a SC: \"TAG\" property is missing")
```

### PR DESCRIPTION
**Pull request by kindaro**
Resolve #1.

### CODE REVIEW

**Comment by StephenWakely** [comment]
Nice work, thanks!

If it's not too much trouble, would you be able to make this option configurable?

Something like [here](https://github.com/uffizio/purescript-argonaut-aeson-generic/blob/f8c54d83cbc490599b9fee8467c0e38993b4f0a7/src/Data/Argonaut/Aeson/Options.purs#L7)

```hs
data SumEncoding
  = TaggedObject { tagFieldName :: String, contentsFieldName :: String, tagSingleConstructors :: Boolean }
```

Which would correspond to the Aeson [option](https://hackage.haskell.org/package/aeson-1.5.4.1/docs/Data-Aeson.html#v:defaultOptions).

**Comment by kindaro** [comment]
Sure, I shall add a setting for it. It will take a day or two.

**Comment by kindaro** [comment]
Ready for review.

**Comment by StephenWakely** [comment]
Beautiful! Great work, thankyou so much!

**Pull request merged**
