### PR TITLE
Update to purescript 0.15

### PR DESCRIPTION
**Pull request by bentongxyz**

### CODE REVIEW

**Comment by peterbecich** [comment]
@bentongxyz , please cherry pick https://github.com/bentongxyz/purescript-argonaut-aeson-generic/commit/66dd97a154c8a912121aa09d48a62d62cac1f740 to this branch, I think it will fix the CI pipeline.

**Comment by bentongxyz** [comment]
Its done, CI pipeline looks good! @peterbecich

**Comment by tonicebrian** [comment]
@peterbecich just a friendly reminder asking if you could merge this. And publishing it to the registry (see https://github.com/purescript/registry#publish-a-package ) would be super cool. Let me know if we could help somehow.

**Comment by peterbecich** [comment]
@tonicebrian I am not a repository owner, but I did e-mail @StephenWakely a couple months ago asking for a review

**Comment by StephenWakely** [comment]
> @tonicebrian I am not a repository owner, but I did e-mail @StephenWakely a couple months ago asking for a review

Ah sorry, this fell off my radar. I haven't been using PureScript for a while now and don't really have the confidence to understand how this library works any more. 

@peterbecich I think you indicated you would be happy to take on the maintenance of this library. @coot  would it be possible to give access to @peterbecich so he could merge PRs etc... Thanks.

**Comment by tonicebrian** [comment]
Hi @StephenWakely if @peterbecich can't or doesn't want to take maintenance of the library I would volunteer also since right now I'm working in a Purescript <-> Haskell application and having this working is very important to me.

**Comment by peterbecich** [comment]
@tonicebrian , until this PR is merged can you override it like shown here? https://github.com/peterbecich/halogen-chess/blob/master/packages.dhall#L6

**Comment by tonicebrian** [comment]
Sure I'll do. @peterbecich if you take ownsership it would be super cool to add this package to package-sets. With the new procedure is super easy.

**Comment by StephenWakely** [comment]
> Hi @StephenWakely if @peterbecich can't or doesn't want to take maintenance of the library I would volunteer also since right now I'm working in a Purescript <-> Haskell application and having this working is very important to me.

Hi, so unfortunately I don't have permissions to update the collaborators for this library, this needs to be done by @coot who I believe is pretty busy. 

I'm wondering if it might be worth creating a fork of this library and we can update the README here to point to that? Would you be willing to take that on?

**Comment by peterbecich** [comment]
@StephenWakely @tonicebrian , sorry for the delay. Yes, I would be happy to maintain the fork.

https://github.com/peterbecich/purescript-argonaut-aeson-generic now points to the latest commit of this PR: https://github.com/coot/purescript-argonaut-aeson-generic/pull/17/commits/66dd97a154c8a912121aa09d48a62d62cac1f740

Looking into updating https://pursuit.purescript.org/packages/purescript-argonaut-aeson-generic ; reading https://github.com/purescript/registry#publish-a-package

**Comment by peterbecich** [comment]
@StephenWakely @tonicebrian inquiry made about transferring ownership of the Pursuit package: https://github.com/coot/purescript-argonaut-aeson-generic/issues/18

**Comment by peterbecich** [comment]
https://github.com/bentongxyz/purescript-argonaut-aeson-generic/actions/runs/3746198245

**Pull request merged**
