### PR TITLE
Updated to work with Generic.Rep v6

### PR DESCRIPTION
**Pull request by StephenWakely**
Records no longer have a Generic representation, so we need to use row
types to walk through the fields.

Have also updated the other libraries. The tests pass, it all seems to work and I
have data going back and forth between a Servant server and the Purescript client correctly.

### CODE REVIEW

**Comment by JulianLeviston** [comment]
Any chance we could get this PR merged @coot ?

**Comment by coot** [comment]
I have no intention to maintain this library.  If you'd like I could transfer the repository to you.

**Comment by StephenWakely** [comment]
@coot If you are happy to transfer it to me, I would be happy to take it on.

**Comment by malte-v** [comment]
@coot So could you transfer this repository to @FungusHumungus? I would really appreciate you doing that or merging this PR if you want to keep the repo.

**Review by coot — APPROVED** [review]

**Comment by coot** [comment]
Sorry for a late replay; I send an inviation to @FungusHumungus, he should have `write` access` to it.

**Comment by malte-v** [comment]
Thanks!

**Comment by StephenWakely** [comment]
Awesome. Thankyou so much! I'll take a look at things tomorrow.

**Pull request merged**
